### ISSUE TITLE
The "stand-alone" ncro.owl file

### ISSUE THREAD

**Issue by Huang-OMIT** [OmniSearch/ncro#11]
Alan: Can u verify the following?

The file accessible at http://purl.obolibary.org/obo/ncro.owl needs to be a stand-alone one, merging all relevant individual owl files into a single owl file. Otherwise, if a user only downloads the ncro.owl file alone, it will not work correctly in Protege by itself.

If this is true, we need to make sure that the ncro.owl file is a correctly merged one _before_ the paper submission.

**Comment by alanruttenberg** [comment]
Whichever version of the file that is there should work. It can work by importing or it can work by merging.  Merging requires some tooling that James Overton uses for OBO (a rewrite of a tolls I originally wrote). Someone has to learn how to use it. I think perhaps this would be a good exercise for Harrison. However it isn't essential for release. More important might be to have a reasoned version.

If you look at https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/ncro.yml
You see that there is a PURL for the imports file. During development as I add files I will add PURLs that correspond to them and use those PURL in the import statements. Therefore if someone  loads NCRO, even if NCRO imports other ontologies, those ontologies will also be imported. 

I have to add a PURL for the ChEBI imports, which I will do shortly and then have you verify that the current version loads properly in Protege for you.

**Comment by Huang-OMIT** [comment]
Open "http://raw.githubusercontent.com/OmniSearch/ncro/master/src/ontology/ncro.owl" in Protege, there will be a warning message that the system couldn't locate chebi-imports.owl. I believe that once the PURL for the ChEBI imports is added, this issue should be resolved.

**Comment by alanruttenberg** [comment]
That PURL request is https://github.com/OBOFoundry/purl.obolibrary.org/pull/116
The new PURL will start working once that is committed to master.

**Comment by Huang-OMIT** [comment]
Alan: Harrison already showed me the other day how to merge all relevant ontologies using Protege itself, which seems to be quite nice. Have you ever tried that? OR, we still have to utilized the tool used by James Overton?

**Comment by linikujp** [comment]
There is no problem for me to open the ontology using Protege from :"https://raw.githubusercontent.com/OmniSearch/ncro/master/src/ontology/ncro.owl".

**Comment by Huang-OMIT** [comment]
Now I do not have any problems either. I believe the PURL request for ChEBI was already committed.

**Comment by alanruttenberg** [comment]
I would rather use James' tools. I don't trust protege not to make mistakes.

**Comment by Huang-OMIT** [comment]
Alan: "Therefore if someone loads NCRO, even if NCRO imports other ontologies, those ontologies will also be imported." I agreed. At the same time, the consequence is for the OMIT ontology to have two imports.owl files, one from NCRO, and the other from OMIT itself. This can be confusing to users. What do you suggest?

**Comment by alanruttenberg** [comment]
The imports.owl in NCRO will slowly be replaced by ontology specific import files. However the name of an ontology is its ontology-uri and those will be different. It is not uncommon to have same suffix for ontology, for example other ontologies used the xx-imports.owl name for ontofox generated files.

**Comment by alanruttenberg** [comment]
There are only a few terms left in imports.owl now. I'll get the last few out and then retire that file. As far as I know NCRO loads fine, so I'm closing the issue.
