### ISSUE TITLE
review of ncro

### ISSUE THREAD

**Issue by Huang-OMIT** [OmniSearch/ncro#12]
1. "cell" needs to be imported from CL (0000000) rather than GO (0005623).
2. "derived_into" and "has_agent" have "#" in their URIs.
3. ontology-metadata.owl appears in both Direct and Indirect Imports in Protege.
4. Is it time-consuming to add "id" annotation for NCRO terms? Especially, those terms at higher levels.

**Comment by alanruttenberg** [comment]
1. CL will be switching to use the GO TERM and deprecating CL_0000000
2. Has_agent has no uses IIRC. If so it will be removed. 
3. Is harmless and will occur frequently. All it means is that an ontology that is imported also imports ontology metadata. Many do. 
4. The id attribute is not good practice. It confuses people as to what the ID is, contributing to interoperability problems. Ditto "alternative id". 
   The official ids are the PURLs, and the PURLs can be written correctly using curies

**Comment by Huang-OMIT** [comment]
1. Got it.
2. Do we need to remove both "derived_into" and "has_agent?"
3. Got it.
4. GO, ChEBI, and SO, etc. are using the id attribute. Having such annotations makes the ontology terms easier to be read by humans. For example, "cellular_component" has an id "GO:0005575;" thus, in Protege, we do not need to move the mouse over the term to see its purl. Anyway, this issue is not an important one before the paper submission.

**Comment by alanruttenberg** [comment]
1. I was tending to keep an inverse of any relation that was used. So I would drop has_agent only. But I am flexible on this issue.
2. GO, ChEBI and SO include that field for OBO format legacy reasons. They should probably be removed there too. You can download the URI plugin from http://code.google.com/p/co-ode-owl-plugins/downloads/list. This gives you a view which you can add to your screen that shows the URI.

**Comment by Huang-OMIT** [comment]
I also tend to keep "derived_into" but it has "#" in the URI...

**Comment by alanruttenberg** [comment]
that should be gone now
