### ISSUE TITLE
Four quick fixes in ncro.owl

### ISSUE THREAD

**Issue by Huang-OMIT** [OmniSearch/ncro#14]
(1)
<rdf:RDF xmlns="http://purl.obolibrary.org/obo/ncro-obo-WorkingVersion-06302015.owl#"
needs to be changed to:
<rdf:RDF xmlns="http://purl.obolibrary.org/obo/ncro.owl#"

(2)
xml:base="http://purl.obolibrary.org/obo/ncro-obo-WorkingVersion-06302015.owl"
needs to be changed to:
xml:base="http://purl.obolibrary.org/obo/ncro.owl"

(3)

needs to be changed to:

(4)
<owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/ncro-obo-WorkingVersion-06302015.owl#IAO_0000117"/>
needs to be changed to:
<owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/IAO_0000117"/>

BTW, a quick question: the ncro.owl file contains a non-existing URL (http://purl.obolibrary.org/obo/ncro-obo-WorkingVersion-06302015.owl), why it can still be opened in Protege without errors?

**Comment by Huang-OMIT** [comment]
For some reason, (3) and (4) were not included in the original message. Here they are:

(3)



needs to be changed to:



(4)
<owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/ncro-obo-WorkingVersion-06302015.owl#IAO_0000117"/>
needs to be changed to:
<owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/IAO_0000117"/>

**Comment by Huang-OMIT** [comment]
Still not showing...Try again:

(3)



needs to be changed to:



(4)
<owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/ncro-obo-WorkingVersion-06302015.owl#IAO_0000117"/>
needs to be changed to:
<owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/IAO_0000117"/>

**Comment by Huang-OMIT** [comment]
Alan: I gave up. Will shoot you an email now...

**Comment by alanruttenberg** [comment]
(1) and (2) don't need to be changed, just removed or changed to http://purl.obolibrary.org/obo/. The xml:base is the default prefix for relative URLs. However we don't have relative URLs (deliberately) and http://purl.obolibrary.org/obo/ncro.owl# would be wrong if we did - it would be http://purl.obolibrary.org/obo/

Regarding your missing lines, code like that needs to be with a certain markdown directive. Put three backticks '```' before and after the block that should be considered literal.

```
<!-- http://purl.obolibrary.org/obo/ncro-obo-WorkingVersion-06302015.owl#IAO_0000117 -->
needs to be changed to:
<!-- http://purl.obolibrary.org/obo/IAO_0000117 -->
```

**Comment by Huang-OMIT** [comment]
Good to know these explanations.
