### ISSUE TITLE
Inaccurate "Number of Terms" and "Detailed Statistics" on Ontobee

### ISSUE THREAD

**Issue by Huang-OMIT** [OmniSearch/ncro#16]
Alan: Both "Number of Terms (including imported terms)" and "Detailed Statistics" on Ontobee provide inaccurate information for ncro (and omit as well). Any idea how to fix this issue?

**Comment by alanruttenberg** [comment]
This should be submitted as a bug report to ontobee. Their tracker is https://github.com/OntoZoo/ontobee/issues
